/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bodega;

/**Conexion ala BD**/

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
/**Importaciones para la swing**/
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**Importaciones para la tabla**/
import javax.swing.table.DefaultTableModel;



/**Conexion hacia otras ventanas del menu**/  //1
import Empleados.KrokEmple;     //2
import Empleados.NuevoProducto; //3
import Bodega.Bodega1;           //4
import Bodega.SalaVenta;        //5
import krocbites2.Login;      //6

/**
 *
 * @author anoni
 */

public class Bodega1 extends javax.swing.JFrame {
    DefaultTableModel dtm=new DefaultTableModel ();
 
  
 
    public Bodega1() {
        initComponents();
         this.setLocationRelativeTo(this);
         
         this.setLocationRelativeTo(null);
         /**Implementacion para lectura de tbla**/
        String[] titulo = new String[]{"Codigo:", "Nombre", "Cantidad", "Precio", "Descripcion"};
                 dtm.setColumnIdentifiers(titulo);
                 Tabla.setModel(dtm);
               
    }
                
    //Metodo de agregar en la tabla
    void agregar(){
        dtm.addRow(new Object[]{
            cod.getText(),nomb.getText(),cant.getText(),pre.getText(),desc.getText()
        });
    }
    //Metodo para eliminar datos de tablas
    void eliminar(){
        int fila=Tabla.getSelectedRow();
        dtm.removeRow(fila);
    }
    //Metodo para modificar datos de tbla
    void modificar(){
        int fila=Tabla.getSelectedRow();
        dtm.setValueAt(cod.getText(),  fila, 0);
        dtm.setValueAt(nomb.getText(), fila, 1); 
        dtm.setValueAt(cant.getText(), fila, 2);
        dtm.setValueAt(pre.getText(),  fila, 3);
        dtm.setValueAt(desc.getText(), fila, 4);        
    }
    //Metodo para limpiar datos de tbla
    void limpiar(){
        int fila=Tabla.getSelectedRow();
       for (int i=0;i<fila;i++) {
                dtm.removeRow(0);
        
 }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RegistroPanel = new javax.swing.JPanel();
        EmpleadoPanel = new javax.swing.JPanel();
        BodegaPanel = new javax.swing.JPanel();
        Emple = new javax.swing.JLabel();
        SalaVentaPanel = new javax.swing.JPanel();
        Regis = new javax.swing.JLabel();
        CerrarPanel = new javax.swing.JPanel();
        SalirPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Sali = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Sala = new javax.swing.JLabel();
        Bode = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        nue = new javax.swing.JButton();
        agre = new javax.swing.JButton();
        modi = new javax.swing.JButton();
        eli = new javax.swing.JButton();
        limp = new javax.swing.JButton();
        desc = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        cant = new javax.swing.JTextField();
        nomb = new javax.swing.JTextField();
        cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 196, 222));

        jPanel5.setBackground(new java.awt.Color(176, 196, 222));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        RegistroPanel.setBackground(new java.awt.Color(176, 196, 222));
        RegistroPanel.setForeground(new java.awt.Color(0, 0, 0));
        RegistroPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel);
        RegistroPanel.setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.add(RegistroPanel);

        EmpleadoPanel.setBackground(new java.awt.Color(176, 196, 222));
        EmpleadoPanel.setForeground(new java.awt.Color(0, 0, 0));
        EmpleadoPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout EmpleadoPanelLayout = new javax.swing.GroupLayout(EmpleadoPanel);
        EmpleadoPanel.setLayout(EmpleadoPanelLayout);
        EmpleadoPanelLayout.setHorizontalGroup(
            EmpleadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        EmpleadoPanelLayout.setVerticalGroup(
            EmpleadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.add(EmpleadoPanel);

        BodegaPanel.setBackground(new java.awt.Color(176, 196, 222));
        BodegaPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        Emple.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Emple.setForeground(new java.awt.Color(0, 0, 0));
        Emple.setText("Empleados");
        Emple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BodegaPanelLayout = new javax.swing.GroupLayout(BodegaPanel);
        BodegaPanel.setLayout(BodegaPanelLayout);
        BodegaPanelLayout.setHorizontalGroup(
            BodegaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Emple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        BodegaPanelLayout.setVerticalGroup(
            BodegaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Emple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.add(BodegaPanel);

        SalaVentaPanel.setBackground(new java.awt.Color(176, 196, 222));
        SalaVentaPanel.setForeground(new java.awt.Color(6, 47, 64));
        SalaVentaPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        Regis.setBackground(new java.awt.Color(0, 0, 0));
        Regis.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Regis.setForeground(new java.awt.Color(0, 0, 0));
        Regis.setText("Registro de producto");
        Regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SalaVentaPanelLayout = new javax.swing.GroupLayout(SalaVentaPanel);
        SalaVentaPanel.setLayout(SalaVentaPanelLayout);
        SalaVentaPanelLayout.setHorizontalGroup(
            SalaVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        SalaVentaPanelLayout.setVerticalGroup(
            SalaVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaVentaPanelLayout.createSequentialGroup()
                .addComponent(Regis, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(SalaVentaPanel);

        CerrarPanel.setBackground(new java.awt.Color(176, 196, 222));
        CerrarPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout CerrarPanelLayout = new javax.swing.GroupLayout(CerrarPanel);
        CerrarPanel.setLayout(CerrarPanelLayout);
        CerrarPanelLayout.setHorizontalGroup(
            CerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        CerrarPanelLayout.setVerticalGroup(
            CerrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.add(CerrarPanel);

        SalirPanel.setBackground(new java.awt.Color(176, 196, 222));
        SalirPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout SalirPanelLayout = new javax.swing.GroupLayout(SalirPanel);
        SalirPanel.setLayout(SalirPanelLayout);
        SalirPanelLayout.setHorizontalGroup(
            SalirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalirPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SalirPanelLayout.setVerticalGroup(
            SalirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalirPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(SalirPanel);

        Sali.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Sali.setForeground(new java.awt.Color(0, 0, 0));
        Sali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir1.png.png"))); // NOI18N
        Sali.setFocusable(false);
        Sali.setRequestFocusEnabled(false);
        Sali.setVerifyInputWhenFocusTarget(false);
        Sali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaliMouseClicked(evt);
            }
        });

        Cerrar.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(0, 0, 0));
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cerrar.png"))); // NOI18N
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        Sala.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Sala.setForeground(new java.awt.Color(0, 0, 0));
        Sala.setText("Sala de ventas");
        Sala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalaMouseClicked(evt);
            }
        });

        Bode.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Bode.setForeground(new java.awt.Color(0, 0, 0));
        Bode.setText("Bodega");
        Bode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BodeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sali, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Sala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addComponent(Bode, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bode, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sala, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(366, 366, 366)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(Sali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Cerrar.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(6, 47, 64));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DatosBod.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        nue.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nue.setForeground(new java.awt.Color(0, 0, 0));
        nue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add2.png"))); // NOI18N
        nue.setText("Nuevo");
        nue.setBorder(null);
        nue.setBorderPainted(false);
        nue.setContentAreaFilled(false);
        nue.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add3.png"))); // NOI18N
        nue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nue.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add3.png"))); // NOI18N
        nue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueActionPerformed(evt);
            }
        });

        agre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        agre.setForeground(new java.awt.Color(0, 0, 0));
        agre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar1.png"))); // NOI18N
        agre.setText("Agregar");
        agre.setBorder(null);
        agre.setBorderPainted(false);
        agre.setContentAreaFilled(false);
        agre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        agre.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar2.png"))); // NOI18N
        agre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreActionPerformed(evt);
            }
        });

        modi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        modi.setForeground(new java.awt.Color(0, 0, 0));
        modi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mod2.png"))); // NOI18N
        modi.setText("Modificar");
        modi.setBorder(null);
        modi.setBorderPainted(false);
        modi.setContentAreaFilled(false);
        modi.setDefaultCapable(false);
        modi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        modi.setSelected(true);
        modi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modify.ai.png"))); // NOI18N
        modi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiActionPerformed(evt);
            }
        });

        eli.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eli.setForeground(new java.awt.Color(0, 0, 0));
        eli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dele1i.png"))); // NOI18N
        eli.setText("Eliminar");
        eli.setBorder(null);
        eli.setBorderPainted(false);
        eli.setContentAreaFilled(false);
        eli.setDefaultCapable(false);
        eli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dele2.png"))); // NOI18N
        eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliActionPerformed(evt);
            }
        });

        limp.setText("LIMPIAR");
        limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpActionPerformed(evt);
            }
        });

        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });

        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripcion:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nue, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(modi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(agre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(modi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpActionPerformed
        //Accion de limpiar datos de tbla
        limpiar();
    }//GEN-LAST:event_limpActionPerformed

    private void eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliActionPerformed
        //Accion de eliminar datos de tabla
        eliminar();
    }//GEN-LAST:event_eliActionPerformed

    private void modiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiActionPerformed
        //Accion de modificar datos de tbla
        modificar();
    }//GEN-LAST:event_modiActionPerformed

    private void agreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreActionPerformed

        // Accion de guardar datos de tablas
        agregar();
        JOptionPane.showMessageDialog(null,"Agregado con exito");
    }//GEN-LAST:event_agreActionPerformed

    private void nueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        //accion de abrir ventana sala venta
        this.dispose();
        Login cerra= new Login ();
        cerra.setVisible(true);
    }//GEN-LAST:event_CerrarMouseClicked

    private void SaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaliMouseClicked

        //accion de salir
        System.exit(0);
    }//GEN-LAST:event_SaliMouseClicked

    private void SalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaMouseClicked
        //accion de abrir ventana sala venta
        this.dispose();
        SalaVenta vent= new SalaVenta ();
        vent.setVisible(true);
    }//GEN-LAST:event_SalaMouseClicked

    private void BodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BodeMouseClicked
        //accion de abrir ventana Bodega
        this.dispose();
        Bodega1 bod= new Bodega1();
        bod.setVisible(true);
    }//GEN-LAST:event_BodeMouseClicked

    private void RegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisMouseClicked
        //accion de abrir ventana de nuevo producto
        this.dispose();
        NuevoProducto nuev= new NuevoProducto();
        nuev.setVisible(true);
    }//GEN-LAST:event_RegisMouseClicked

    private void EmpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpleMouseClicked
        //accion de abrir ventana sala venta
        this.dispose();
        SalaVenta vent= new SalaVenta ();
        vent.setVisible(true);
    }//GEN-LAST:event_EmpleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bodega1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bode;
    private javax.swing.JPanel BodegaPanel;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JPanel CerrarPanel;
    private javax.swing.JLabel Emple;
    private javax.swing.JPanel EmpleadoPanel;
    private javax.swing.JLabel Regis;
    private javax.swing.JPanel RegistroPanel;
    private javax.swing.JLabel Sala;
    private javax.swing.JPanel SalaVentaPanel;
    private javax.swing.JLabel Sali;
    private javax.swing.JPanel SalirPanel;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton agre;
    private javax.swing.JTextField cant;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField desc;
    private javax.swing.JButton eli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limp;
    private javax.swing.JButton modi;
    private javax.swing.JTextField nomb;
    private javax.swing.JButton nue;
    private javax.swing.JTextField pre;
    // End of variables declaration//GEN-END:variables
}
