/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Empleados;


import BDMySQL.ConexionArea;
import BDMySQL.ConexionCargo;
import BDMySQL.ConexionEmpleados;
import  Empleados.NuevoProducto;

import Bodega.SalaVenta;
import Bod.BOD;
import clases.areas;
import clases.cargo;
import clases.empleado;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import krocbites2.Login;


/**
 *
 * @author anoni
 */
public class KrokEmple extends javax.swing.JFrame {
    cargo cr = new cargo();
    ConexionCargo daoC=new ConexionCargo();
    DefaultTableModel modeloCargo=new DefaultTableModel();
    
    
    areas ar = new areas();
    ConexionArea daoA=new ConexionArea();
    DefaultTableModel modeloArea=new DefaultTableModel();
    
    empleado em = new empleado();
    ConexionEmpleados daoE=new ConexionEmpleados();
    DefaultTableModel modeloEmpleados=new DefaultTableModel();
 


    /**
     * Creates new form KrokEmple
     */
    public KrokEmple() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/cocodrilo.png")).getImage());
        this.setLocationRelativeTo(this);
        this.setLocationRelativeTo(null);
        this.setExtendedState(KrokEmple.MAXIMIZED_BOTH);
         listar();
         listarArea();
         EnviarAreas.setEnabled(false);
         EnviarCargos.setEnabled(false);

         
    }
    
    private void listar(){
        List<cargo> lista=daoC.listar();
        modeloCargo=(DefaultTableModel)  tablacargos.getModel();
        Object[] ob=new Object[2];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNombre();
            modeloCargo.addRow(ob);
            
        }
        tablacargos.setModel(modeloCargo);
    }
    
    private void listarArea(){
        List<areas> lista=daoA.listar();
        modeloArea=(DefaultTableModel)  tablaArea.getModel();
        Object[] ob=new Object[2];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdarea();
            ob[1]=lista.get(i).getNomArea();
            modeloArea.addRow(ob);
            
        }
        tablaArea.setModel(modeloArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnBodega = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnSalaVenta = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnAsistencia = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnCerrar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel = new javax.swing.JTabbedPane();
        phome = new javax.swing.JPanel();
        psuarios = new javax.swing.JPanel();
        pcargo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxCargo = new javax.swing.JTextField();
        RegistrarCargos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacargos = new javax.swing.JTable();
        ModificarCargos = new javax.swing.JButton();
        EliminarCargos = new javax.swing.JButton();
        BuscarCargos = new javax.swing.JButton();
        EnviarCargos = new javax.swing.JButton();
        parea = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxIDarea = new javax.swing.JTextField();
        TxNombreArea = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArea = new javax.swing.JTable();
        RegistrarArea = new javax.swing.JButton();
        ModificarAreas = new javax.swing.JButton();
        EliminarAreas = new javax.swing.JButton();
        BuscarArea = new javax.swing.JButton();
        EnviarAreas = new javax.swing.JButton();
        pempleados = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxIDareaEmple = new javax.swing.JTextField();
        TxAreaEmple = new javax.swing.JTextField();
        EmpleAreaBuscar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxEmpleado = new javax.swing.JTextField();
        TxNombreEmple = new javax.swing.JTextField();
        TxApellidoEmple = new javax.swing.JTextField();
        TxDui = new javax.swing.JTextField();
        TxTelefono = new javax.swing.JTextField();
        TxCorreo = new javax.swing.JTextField();
        TipoDoc = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TxIDcargoEmple = new javax.swing.JTextField();
        TxCargoEmple = new javax.swing.JTextField();
        EmpleCargosBuscar = new javax.swing.JButton();
        RegistrarEmple = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaempleado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 196, 222));
        jPanel1.setPreferredSize(new java.awt.Dimension(384, 837));

        jPanel4.setBackground(new java.awt.Color(6, 47, 64));
        jPanel4.setPreferredSize(new java.awt.Dimension(1253, 130));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(176, 196, 222));

        jPanel6.setBackground(new java.awt.Color(144, 169, 191));
        jPanel6.setPreferredSize(new java.awt.Dimension(263, 63));

        btnEmpleados.setBackground(new java.awt.Color(144, 169, 191));
        btnEmpleados.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(null);
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(144, 169, 191));
        jPanel7.setPreferredSize(new java.awt.Dimension(263, 63));

        btnRegistro.setBackground(new java.awt.Color(144, 169, 191));
        btnRegistro.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Registro de producto");
        btnRegistro.setBorder(null);
        btnRegistro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistro.setPreferredSize(new java.awt.Dimension(98, 24));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(144, 169, 191));
        jPanel8.setPreferredSize(new java.awt.Dimension(263, 63));

        btnBodega.setBackground(new java.awt.Color(144, 169, 191));
        btnBodega.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBodega.setForeground(new java.awt.Color(0, 0, 0));
        btnBodega.setText("Bodega");
        btnBodega.setBorder(null);
        btnBodega.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBodega.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBodega.setPreferredSize(new java.awt.Dimension(98, 24));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBodega, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(144, 169, 191));
        jPanel9.setAutoscrolls(true);
        jPanel9.setPreferredSize(new java.awt.Dimension(263, 63));

        btnSalaVenta.setBackground(new java.awt.Color(144, 169, 191));
        btnSalaVenta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSalaVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnSalaVenta.setText("Sala de venta");
        btnSalaVenta.setBorder(null);
        btnSalaVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalaVenta.setPreferredSize(new java.awt.Dimension(98, 24));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(144, 169, 191));
        jPanel10.setPreferredSize(new java.awt.Dimension(263, 63));

        btnAsistencia.setBackground(new java.awt.Color(144, 169, 191));
        btnAsistencia.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAsistencia.setForeground(new java.awt.Color(0, 0, 0));
        btnAsistencia.setText("Asistencia");
        btnAsistencia.setBorder(null);
        btnAsistencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setPreferredSize(new java.awt.Dimension(98, 24));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(144, 169, 191));
        jPanel11.setPreferredSize(new java.awt.Dimension(263, 63));

        btnCerrar1.setBackground(new java.awt.Color(144, 169, 191));
        btnCerrar1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCerrar1.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar1.setText("Cerrar sesion");
        btnCerrar1.setBorder(null);
        btnCerrar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar1.setPreferredSize(new java.awt.Dimension(98, 24));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(6, 47, 64));
        jPanel2.setPreferredSize(new java.awt.Dimension(1253, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DatosEmple.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setForeground(new java.awt.Color(0, 0, 0));
        panel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        phome.setBackground(new java.awt.Color(255, 255, 255));
        phome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        panel.addTab("Home", phome);

        psuarios.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout psuariosLayout = new javax.swing.GroupLayout(psuarios);
        psuarios.setLayout(psuariosLayout);
        psuariosLayout.setHorizontalGroup(
            psuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        psuariosLayout.setVerticalGroup(
            psuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        panel.addTab("Usuarios", psuarios);

        pcargo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID:");

        TxID.setBackground(new java.awt.Color(255, 255, 255));
        TxID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre:");

        TxCargo.setBackground(new java.awt.Color(255, 255, 255));
        TxCargo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        RegistrarCargos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RegistrarCargos.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarCargos.setText("Registrar");
        RegistrarCargos.setContentAreaFilled(false);
        RegistrarCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarCargos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarCargos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar2.png"))); // NOI18N
        RegistrarCargos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegistrarCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegistrarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCargosActionPerformed(evt);
            }
        });

        tablacargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargos"
            }
        ));
        tablacargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacargos);

        ModificarCargos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ModificarCargos.setForeground(new java.awt.Color(0, 0, 0));
        ModificarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar1.png"))); // NOI18N
        ModificarCargos.setText("Modificar");
        ModificarCargos.setContentAreaFilled(false);
        ModificarCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModificarCargos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar1.png"))); // NOI18N
        ModificarCargos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar2.png"))); // NOI18N
        ModificarCargos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ModificarCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModificarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCargosActionPerformed(evt);
            }
        });

        EliminarCargos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EliminarCargos.setForeground(new java.awt.Color(0, 0, 0));
        EliminarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar1.png"))); // NOI18N
        EliminarCargos.setText("Eliminar");
        EliminarCargos.setContentAreaFilled(false);
        EliminarCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarCargos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar1.png"))); // NOI18N
        EliminarCargos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
        EliminarCargos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EliminarCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCargosActionPerformed(evt);
            }
        });

        BuscarCargos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BuscarCargos.setForeground(new java.awt.Color(0, 0, 0));
        BuscarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        BuscarCargos.setText("Buscar");
        BuscarCargos.setContentAreaFilled(false);
        BuscarCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuscarCargos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        BuscarCargos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar2.png"))); // NOI18N
        BuscarCargos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BuscarCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BuscarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCargosActionPerformed(evt);
            }
        });

        EnviarCargos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EnviarCargos.setForeground(new java.awt.Color(0, 0, 0));
        EnviarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar1.png"))); // NOI18N
        EnviarCargos.setText("Enviar");
        EnviarCargos.setContentAreaFilled(false);
        EnviarCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EnviarCargos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
        EnviarCargos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar2.png"))); // NOI18N
        EnviarCargos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EnviarCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EnviarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarCargosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pcargoLayout = new javax.swing.GroupLayout(pcargo);
        pcargo.setLayout(pcargoLayout);
        pcargoLayout.setHorizontalGroup(
            pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcargoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(TxID)))
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BuscarCargos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pcargoLayout.createSequentialGroup()
                                .addComponent(RegistrarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ModificarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnviarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pcargoLayout.setVerticalGroup(
            pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcargoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistrarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnviarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panel.addTab("Cargo", pcargo);

        parea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ID:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");

        TxIDarea.setBackground(new java.awt.Color(255, 255, 255));
        TxIDarea.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        TxNombreArea.setBackground(new java.awt.Color(255, 255, 255));
        TxNombreArea.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        tablaArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Area"
            }
        ));
        tablaArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAreaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaArea);

        RegistrarArea.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RegistrarArea.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarArea.setText("Registrar");
        RegistrarArea.setContentAreaFilled(false);
        RegistrarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarArea.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarArea.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar2.png"))); // NOI18N
        RegistrarArea.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegistrarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegistrarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAreaActionPerformed(evt);
            }
        });

        ModificarAreas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ModificarAreas.setForeground(new java.awt.Color(0, 0, 0));
        ModificarAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar1.png"))); // NOI18N
        ModificarAreas.setText("Modificar");
        ModificarAreas.setContentAreaFilled(false);
        ModificarAreas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModificarAreas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar1.png"))); // NOI18N
        ModificarAreas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar2.png"))); // NOI18N
        ModificarAreas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ModificarAreas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModificarAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarAreasActionPerformed(evt);
            }
        });

        EliminarAreas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EliminarAreas.setForeground(new java.awt.Color(0, 0, 0));
        EliminarAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar1.png"))); // NOI18N
        EliminarAreas.setText("Eliminar");
        EliminarAreas.setContentAreaFilled(false);
        EliminarAreas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarAreas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar1.png"))); // NOI18N
        EliminarAreas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
        EliminarAreas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EliminarAreas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAreasActionPerformed(evt);
            }
        });

        BuscarArea.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BuscarArea.setForeground(new java.awt.Color(0, 0, 0));
        BuscarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        BuscarArea.setText("Buscar");
        BuscarArea.setContentAreaFilled(false);
        BuscarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuscarArea.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        BuscarArea.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar2.png"))); // NOI18N
        BuscarArea.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BuscarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BuscarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAreaActionPerformed(evt);
            }
        });

        EnviarAreas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EnviarAreas.setForeground(new java.awt.Color(0, 0, 0));
        EnviarAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar1.png"))); // NOI18N
        EnviarAreas.setText("Enviar");
        EnviarAreas.setContentAreaFilled(false);
        EnviarAreas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EnviarAreas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
        EnviarAreas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar2.png"))); // NOI18N
        EnviarAreas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EnviarAreas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EnviarAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarAreasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pareaLayout = new javax.swing.GroupLayout(parea);
        parea.setLayout(pareaLayout);
        pareaLayout.setHorizontalGroup(
            pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pareaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pareaLayout.createSequentialGroup()
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pareaLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(TxIDarea, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(pareaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(TxNombreArea)))
                        .addGap(261, 261, 261))
                    .addGroup(pareaLayout.createSequentialGroup()
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BuscarArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pareaLayout.createSequentialGroup()
                                .addComponent(RegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ModificarAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnviarAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        pareaLayout.setVerticalGroup(
            pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pareaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pareaLayout.createSequentialGroup()
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxIDarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(43, 43, 43)
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnviarAreas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        panel.addTab("Area", parea);

        pempleados.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("ID:");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Area:");

        EmpleAreaBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpleAreaBuscar.setForeground(new java.awt.Color(0, 0, 0));
        EmpleAreaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        EmpleAreaBuscar.setText("Buscar");
        EmpleAreaBuscar.setContentAreaFilled(false);
        EmpleAreaBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EmpleAreaBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        EmpleAreaBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar2.png"))); // NOI18N
        EmpleAreaBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EmpleAreaBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EmpleAreaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleAreaBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxIDareaEmple)
                    .addComponent(TxAreaEmple)
                    .addComponent(EmpleAreaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxIDareaEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxAreaEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmpleAreaBuscar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Apellido:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tipo doc:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("DUI:");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Telefono:");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Correo:");

        TipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUI", "Pasaporte", "NIE" }));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxNombreEmple)
                            .addComponent(TxApellidoEmple)
                            .addComponent(TxDui)
                            .addComponent(TxTelefono)
                            .addComponent(TxCorreo)
                            .addComponent(TipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxNombreEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxApellidoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID:");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Cargo:");

        EmpleCargosBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EmpleCargosBuscar.setForeground(new java.awt.Color(0, 0, 0));
        EmpleCargosBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        EmpleCargosBuscar.setText("Buscar");
        EmpleCargosBuscar.setContentAreaFilled(false);
        EmpleCargosBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EmpleCargosBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N
        EmpleCargosBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar2.png"))); // NOI18N
        EmpleCargosBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EmpleCargosBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EmpleCargosBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleCargosBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxIDcargoEmple)
                    .addComponent(TxCargoEmple)
                    .addComponent(EmpleCargosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxIDcargoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxCargoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpleCargosBuscar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        RegistrarEmple.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RegistrarEmple.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarEmple.setText("Registrar");
        RegistrarEmple.setContentAreaFilled(false);
        RegistrarEmple.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarEmple.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        RegistrarEmple.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar2.png"))); // NOI18N
        RegistrarEmple.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegistrarEmple.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegistrarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEmpleActionPerformed(evt);
            }
        });

        tablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Tipo doc", "Documento", "IdArea", "Area", "IdCargo", "Cargo", "Telefono ", "Correo"
            }
        ));
        jScrollPane3.setViewportView(tablaempleado);

        javax.swing.GroupLayout pempleadosLayout = new javax.swing.GroupLayout(pempleados);
        pempleados.setLayout(pempleadosLayout);
        pempleadosLayout.setHorizontalGroup(
            pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pempleadosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pempleadosLayout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pempleadosLayout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RegistrarEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pempleadosLayout.setVerticalGroup(
            pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pempleadosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pempleadosLayout.createSequentialGroup()
                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(RegistrarEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel.addTab("Empleados", pempleados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panel)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //**TERMINA ACCIONES DE NAV**//
    ////
    //*CARGOS*//
    ////
    //* ACCION DE LA TABLA CARGOS Y BD*//
    private void tablacargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacargosMouseClicked
      int fila=tablacargos.getSelectedRow();
      TxID.setText(tablacargos.getValueAt(fila, 0).toString());
      TxCargo.setText(tablacargos.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablacargosMouseClicked
    //* ACCION DEL BOTON REGISTRAR EN LA SECCION CARGOS Y BD*//
    private void RegistrarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCargosActionPerformed
        cr.setNombre(TxCargo.getText());
        if(daoC.insertar(cr)){
            JOptionPane.showMessageDialog(null, "Cargo registrado con exito");
              limpiarDatosCargo();
              limpiarTablaCargo();
              listar();
        }else{
            JOptionPane.showMessageDialog(null, "Error al registrar");
        }
    }//GEN-LAST:event_RegistrarCargosActionPerformed
    //* ACCION DEL BOTON MODIFICAR EN TABLA CARGOS Y BD*//
    private void ModificarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCargosActionPerformed
        int fila=tablacargos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un cargo");
        }
        else{
            cr.setId(Integer.parseInt(TxID.getText()));
             cr.setNombre(TxCargo.getText());
             if(daoC.editar(cr)){
                 JOptionPane.showMessageDialog(null, "Se modifico con exito");
                  limpiarDatosCargo();
                  limpiarTablaCargo();
                  listar();
             }else{
                 JOptionPane.showMessageDialog(null, "Fallo modificar");
             }
        }
    }//GEN-LAST:event_ModificarCargosActionPerformed
    //* ACCION DEL BOTON ELIMINAR EN TABLA CARGOS Y BD*//
    private void EliminarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCargosActionPerformed
        if(!TxID.getText().isEmpty()){
            int confirmacion= JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de eliminar el cargo?","Confirmacion",2);
            if(confirmacion ==0){
                cr.setId(Integer.parseInt(TxID.getText()));
                 daoC.eliminar(cr);
                 limpiarDatosCargo();
                 limpiarTablaCargo();
                 listar();
            }
        }
    }//GEN-LAST:event_EliminarCargosActionPerformed
    //* ACCION DEL BOTON BUSCAR EN TABLA CARGOS Y BD*//
    private void BuscarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCargosActionPerformed

        cr.setId(Integer.parseInt(TxID.getText()));
        if(daoC.buscar(cr)){
            TxID.setText(cr.getId()+"");
            TxCargo.setText(cr.getNombre());
        }else{
            JOptionPane.showConfirmDialog(null, "El cargo no existe");
            TxID.setText("");
            TxCargo.setText("");
        } 
         //* TERMINAN ACCION DE TABLA CARGOS Y BD*//
    }//GEN-LAST:event_BuscarCargosActionPerformed
    ////
    //*AREAS*//
    ////
    //* ACCION REGISTRAR DE LA TABLA AREAS Y BD*//
    private void RegistrarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAreaActionPerformed
        ar.setNomArea(TxNombreArea.getText());
        if(daoA.insertar(ar)){
            JOptionPane.showMessageDialog(null, "Area ingresada con exito");
              limpiarDatosArea();
              limpiarTablaArea();
              listarArea();
        }else{
            JOptionPane.showMessageDialog(null, "Error al registrar el area");
        }
      
    }//GEN-LAST:event_RegistrarAreaActionPerformed

    private void ModificarAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarAreasActionPerformed
       int fila=tablaArea.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione una area");
        }
        else{
            ar.setIdarea(Integer.parseInt(TxIDarea.getText()));
            ar.setNomArea(TxNombreArea.getText());
             if(daoA.editar(ar)){
                 JOptionPane.showMessageDialog(null, "Se modifico con exito");
                  limpiarDatosArea();
                  limpiarTablaArea();
                  listarArea();
             }else{
                 JOptionPane.showMessageDialog(null, "Fallo modificar");
             }
        }
    }//GEN-LAST:event_ModificarAreasActionPerformed
        //* ACCION DE LA TABLA CARGOS Y BD*//
    private void tablaAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAreaMouseClicked
       int fila=tablaArea.getSelectedRow();
      TxIDarea.setText(tablaArea.getValueAt(fila, 0).toString());
      TxNombreArea.setText(tablaArea.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablaAreaMouseClicked

    private void EliminarAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAreasActionPerformed
        if(!TxIDarea.getText().isEmpty()){
            int confirmacion= JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de eliminar la area?","Confirmacion",2);
            if(confirmacion ==0){
                ar.setIdarea(Integer.parseInt(TxIDarea.getText()));
                daoA.eliminar(ar);
                limpiarDatosArea();
                limpiarTablaArea();
                listarArea();
            }
        }
    }//GEN-LAST:event_EliminarAreasActionPerformed

    private void BuscarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAreaActionPerformed
        ar.setIdarea(Integer.parseInt(TxIDarea.getText()));
        if(daoA.buscar(ar)){
            TxIDarea.setText(ar.getIdarea()+"");
            TxNombreArea.setText(ar.getNomArea());
        }else{
            JOptionPane.showConfirmDialog(null, "El cargo no existe");
            TxID.setText("");
            TxCargo.setText("");
        } 
         //* TERMINAN ACCION DE TABLA CARGOS Y BD*//
    }//GEN-LAST:event_BuscarAreaActionPerformed

    private void RegistrarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEmpleActionPerformed
       em.setNombre(TxNombreEmple.getText());
        em.setApellido(TxApellidoEmple.getText());
        em.setTipodoc(TipoDoc.getSelectedItem().toString());
        em.setDocumento(TxDui.getText());
        em.setIdArea(Integer.parseInt(TxIDareaEmple.getText()));
        em.setIdCargo(Integer.parseInt(TxIDcargoEmple.getText()));
        em.setTelefono(TxTelefono.getText());
        em.setCorreo(TxCorreo.getText());
        if(daoE.insertar(em)){
            JOptionPane.showMessageDialog(null, "Empleado registrado con exito");
            //limpiarDatosEmpleado();
            //limpiarTablaEmpleado();
            //listarEmpleado();
            //cantEmpleados();
        }else{
            JOptionPane.showMessageDialog(null, "Error Al Registrar el Empleado");
        }
        
        
        
        
    }//GEN-LAST:event_RegistrarEmpleActionPerformed

    private void EmpleAreaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleAreaBuscarActionPerformed
     EnviarAreas.setEnabled(true);
     panel.setSelectedComponent(parea);


    }//GEN-LAST:event_EmpleAreaBuscarActionPerformed

    private void EmpleCargosBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleCargosBuscarActionPerformed
        EnviarCargos.setEnabled(true);
     panel.setSelectedComponent(pcargo);

    }//GEN-LAST:event_EmpleCargosBuscarActionPerformed

    private void EnviarAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarAreasActionPerformed
        TxIDareaEmple.setText(TxIDarea.getText());
        TxAreaEmple.setText(TxNombreArea.getText());
        EnviarAreas.setEnabled(false);
        panel.setSelectedComponent(pempleados);
    }//GEN-LAST:event_EnviarAreasActionPerformed

    private void EnviarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarCargosActionPerformed
        TxIDcargoEmple.setText(TxID.getText());
        TxCargoEmple.setText(TxCargo.getText());
        EnviarCargos.setEnabled(false);
        panel.setSelectedComponent(pempleados);
    }//GEN-LAST:event_EnviarCargosActionPerformed
    ////
    /**LIMPIAR TX Y TABLA DE CARGOS **/
    ////
    void limpiarDatosCargo(){
        TxID.setText("");
        TxCargo.setText("");
    }
    void limpiarTablaCargo(){
        for(int i=0;i<modeloCargo.getRowCount();i++){
        modeloCargo.removeRow(i);
        i=0-1;
        }
     }
    ////
    /**METODO DE LIMPIAR EN LOS TX Y TABLA AREAS**/
    ////
    void limpiarDatosArea(){
        TxIDarea.setText("");
        TxNombreArea.setText("");
    }
    void limpiarTablaArea(){
        for(int i=0;i<modeloArea.getRowCount();i++){
        modeloArea.removeRow(i);
        i=0-1;
        }
     }



    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrokEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrokEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrokEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrokEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrokEmple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarArea;
    private javax.swing.JButton BuscarCargos;
    private javax.swing.JButton EliminarAreas;
    private javax.swing.JButton EliminarCargos;
    private javax.swing.JButton EmpleAreaBuscar;
    private javax.swing.JButton EmpleCargosBuscar;
    private javax.swing.JButton EnviarAreas;
    private javax.swing.JButton EnviarCargos;
    private javax.swing.JButton ModificarAreas;
    private javax.swing.JButton ModificarCargos;
    private javax.swing.JButton RegistrarArea;
    private javax.swing.JButton RegistrarCargos;
    private javax.swing.JButton RegistrarEmple;
    private javax.swing.JComboBox<String> TipoDoc;
    private javax.swing.JTextField TxApellidoEmple;
    private javax.swing.JTextField TxAreaEmple;
    private javax.swing.JTextField TxCargo;
    private javax.swing.JTextField TxCargoEmple;
    private javax.swing.JTextField TxCorreo;
    private javax.swing.JTextField TxDui;
    private javax.swing.JTextField TxEmpleado;
    private javax.swing.JTextField TxID;
    private javax.swing.JTextField TxIDarea;
    private javax.swing.JTextField TxIDareaEmple;
    private javax.swing.JTextField TxIDcargoEmple;
    private javax.swing.JTextField TxNombreArea;
    private javax.swing.JTextField TxNombreEmple;
    private javax.swing.JTextField TxTelefono;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBodega;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalaVenta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel parea;
    private javax.swing.JPanel pcargo;
    private javax.swing.JPanel pempleados;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel psuarios;
    private javax.swing.JTable tablaArea;
    private javax.swing.JTable tablacargos;
    private javax.swing.JTable tablaempleado;
    // End of variables declaration//GEN-END:variables
}
