/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panta_principal;


import Panta_principal.Catego;
import java.awt.BorderLayout;

/**
 *
 * @author anoni
 */
public class Panta_inicio extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Panta_inicio
     */
    public Panta_inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        //
        //
        Inicio  Ini = new Inicio ();
        Ini.setSize(1264, 762);
        Ini.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(Ini,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
  
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new PANELES.PanelRound();
        panelRound3 = new PANELES.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        BTON_INICIO = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_CATE = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_CLIENTES = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_ENTRA = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_PROVE = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_SALI = new RSMaterialComponent.RSButtonMaterialIconDos();
        BTON_USUARIOS = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        BTON_USUARIOS1 = new RSMaterialComponent.RSButtonMaterialIconDos();
        contenedor = new PANELES.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setEnabled(false);
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);

        panelRound3.setBackground(new java.awt.Color(6, 47, 64));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/path1.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        BTON_INICIO.setBackground(new java.awt.Color(6, 47, 64));
        BTON_INICIO.setText("INICIO");
        BTON_INICIO.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_INICIO.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        BTON_INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_INICIOActionPerformed(evt);
            }
        });

        BTON_CATE.setBackground(new java.awt.Color(6, 47, 64));
        BTON_CATE.setText("CATEGORIAS");
        BTON_CATE.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_CATE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        BTON_CATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_CATEActionPerformed(evt);
            }
        });

        BTON_CLIENTES.setBackground(new java.awt.Color(6, 47, 64));
        BTON_CLIENTES.setText("CLIENTES");
        BTON_CLIENTES.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_CLIENTES.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        BTON_CLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_CLIENTESActionPerformed(evt);
            }
        });

        BTON_ENTRA.setBackground(new java.awt.Color(6, 47, 64));
        BTON_ENTRA.setText("ENTRADAS");
        BTON_ENTRA.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_ENTRA.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_ARROW_DOWN);

        BTON_PROVE.setBackground(new java.awt.Color(6, 47, 64));
        BTON_PROVE.setText("PROVEEDOR");
        BTON_PROVE.setBackgroundHover(new java.awt.Color(93, 158, 193));

        BTON_SALI.setBackground(new java.awt.Color(6, 47, 64));
        BTON_SALI.setText("SALIDAS");
        BTON_SALI.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_SALI.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_ARROW_UP);

        BTON_USUARIOS.setBackground(new java.awt.Color(6, 47, 64));
        BTON_USUARIOS.setText("USUARIOS");
        BTON_USUARIOS.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_USUARIOS.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP_ADD);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        BTON_USUARIOS1.setBackground(new java.awt.Color(6, 47, 64));
        BTON_USUARIOS1.setBackgroundHover(new java.awt.Color(93, 158, 193));
        BTON_USUARIOS1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        BTON_USUARIOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_USUARIOS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BTON_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_PROVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_ENTRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_CLIENTES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_CATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTON_SALI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTON_USUARIOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BTON_INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTON_CATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_CLIENTES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_ENTRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_PROVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_SALI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTON_USUARIOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1261, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTON_CLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_CLIENTESActionPerformed
     
    }//GEN-LAST:event_BTON_CLIENTESActionPerformed

    private void BTON_INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_INICIOActionPerformed
        //ACCION BTN INICIO
        BTON_INICIO.setSelected(true);
        BTON_CATE.setSelected(false);
        
        Inicio  Ini = new Inicio ();
        Ini.setSize(1264, 762);
        Ini.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(Ini,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_BTON_INICIOActionPerformed

    private void BTON_CATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_CATEActionPerformed
        //ACCION BTN CATEGORIA
        BTON_CATE.setSelected(true);
        BTON_INICIO.setSelected(false);
       
        Catego ca = new Catego ();
        ca.setSize(1264, 762);
        ca.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(ca,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();

    }//GEN-LAST:event_BTON_CATEActionPerformed

    private void BTON_USUARIOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_USUARIOS1ActionPerformed
      //ACCION DE SALIR
      System.exit(0);
    }//GEN-LAST:event_BTON_USUARIOS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panta_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panta_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panta_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panta_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panta_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_CATE;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_CLIENTES;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_ENTRA;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_INICIO;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_PROVE;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_SALI;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_USUARIOS;
    private RSMaterialComponent.RSButtonMaterialIconDos BTON_USUARIOS1;
    private PANELES.PanelRound contenedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private PANELES.PanelRound panelRound1;
    private PANELES.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
